galaxy_info:
  role_name: DISA
  author: 
  description: 'DISA STIGS for CENTOS 8'

  issue_tracker_url: 

  license: BSD-3-Clause

  min_ansible_version: 2.5

  platforms:
  - name: EL
    versions:
    - 8

  galaxy_tags:
  - system
  - hardening
  - openscap
  - ssg
  - scap
  - security
  - compliance
  - complianceascode
  - disa
  - stig
  - redhatofficial
  - redhat

dependencies: []
